name: test
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy
    env:
      GOOD: sangmin is good man
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variable
        run: echo $GOOD

      - name: Print environment variable
        env:
          GREETING: Hello, world!
        run: echo $GREETING

      - name: Print environment variable2
        run: echo $GREETING
